{"buggy_code": ["#!/usr/bin/python\n\nimport dbus\nimport dbus.service\nimport dbus.mainloop.glib\nimport gobject\nimport slip.dbus.service\nfrom slip.dbus import polkit\nimport os\nclass RunFix(slip.dbus.service.Object):\n    default_polkit_auth_required = \"org.fedoraproject.setroubleshootfixit.write\"\n    def __init__ (self, *p, **k):\n        super(RunFix, self).__init__(*p, **k)\n        \n    @dbus.service.method (\"org.fedoraproject.SetroubleshootFixit\", in_signature='ss', out_signature='s')\n    def run_fix(self, local_id, analysis_id):\n        import commands\n        command = \"sealert -f %s -P %s\" % ( local_id, analysis_id)\n        return commands.getoutput(command)\n\nif __name__ == \"__main__\":\n    mainloop = gobject.MainLoop ()\n    dbus.mainloop.glib.DBusGMainLoop (set_as_default=True)\n    system_bus = dbus.SystemBus ()\n    name = dbus.service.BusName(\"org.fedoraproject.SetroubleshootFixit\", system_bus)\n    object = RunFix(system_bus, \"/org/fedoraproject/SetroubleshootFixit/object\")\n    slip.dbus.service.set_mainloop (mainloop)\n    mainloop.run ()\n"], "fixing_code": ["#!/usr/bin/python\n\nimport dbus\nimport dbus.service\nimport dbus.mainloop.glib\nimport gobject\nimport slip.dbus.service\nfrom slip.dbus import polkit\nimport os\nclass RunFix(slip.dbus.service.Object):\n    default_polkit_auth_required = \"org.fedoraproject.setroubleshootfixit.write\"\n    def __init__ (self, *p, **k):\n        super(RunFix, self).__init__(*p, **k)\n        \n    @dbus.service.method (\"org.fedoraproject.SetroubleshootFixit\", in_signature='ss', out_signature='s')\n    def run_fix(self, local_id, analysis_id):\n        import subprocess\n        command = [\"sealert\", \"-f\", local_id, \"-P\", analysis_id]\n        return subprocess.check_output(command, universal_newlines=True)\n\nif __name__ == \"__main__\":\n    mainloop = gobject.MainLoop ()\n    dbus.mainloop.glib.DBusGMainLoop (set_as_default=True)\n    system_bus = dbus.SystemBus ()\n    name = dbus.service.BusName(\"org.fedoraproject.SetroubleshootFixit\", system_bus)\n    object = RunFix(system_bus, \"/org/fedoraproject/SetroubleshootFixit/object\")\n    slip.dbus.service.set_mainloop (mainloop)\n    mainloop.run ()\n"], "filenames": ["framework/src/SetroubleshootFixit.py"], "buggy_code_start_loc": [17], "buggy_code_end_loc": [20], "fixing_code_start_loc": [17], "fixing_code_end_loc": [20], "type": "CWE-77", "message": "setroubleshoot allows local users to bypass an intended container protection mechanism and execute arbitrary commands by (1) triggering an SELinux denial with a crafted file name, which is handled by the _set_tpath function in audit_data.py or via a crafted (2) local_id or (3) analysis_id field in a crafted XML document to the run_fix function in SetroubleshootFixit.py, related to the subprocess.check_output and commands.getstatusoutput functions, a different vulnerability than CVE-2016-4445.", "other": {"cve": {"id": "CVE-2016-4989", "sourceIdentifier": "secalert@redhat.com", "published": "2017-04-11T18:59:00.353", "lastModified": "2017-04-17T16:36:57.637", "vulnStatus": "Analyzed", "descriptions": [{"lang": "en", "value": "setroubleshoot allows local users to bypass an intended container protection mechanism and execute arbitrary commands by (1) triggering an SELinux denial with a crafted file name, which is handled by the _set_tpath function in audit_data.py or via a crafted (2) local_id or (3) analysis_id field in a crafted XML document to the run_fix function in SetroubleshootFixit.py, related to the subprocess.check_output and commands.getstatusoutput functions, a different vulnerability than CVE-2016-4445."}, {"lang": "es", "value": "Setroubleshoot permite a los usuarios locales evitar un mecanismo de protecci\u00f3n de contenedor previsto y ejecutar comandos arbitrarios al activar una denegaci\u00f3n de SELinux con un nombre de archivo manipulado, que es manejado por la funci\u00f3n _set_tpath en audit_data.py oa trav\u00e9s de un (2) local_id o ( 3) campo analysis_id en un documento XML manipulado a la funci\u00f3n run_fix en SetroubleshootFixit.py, relacionado con las funciones subprocess.check_output y commands.getstatusoutput, una vulnerabilidad diferente de CVE-2016-4445."}], "metrics": {"cvssMetricV30": [{"source": "nvd@nist.gov", "type": "Primary", "cvssData": {"version": "3.0", "vectorString": "CVSS:3.0/AV:L/AC:H/PR:L/UI:N/S:U/C:H/I:H/A:H", "attackVector": "LOCAL", "attackComplexity": "HIGH", "privilegesRequired": "LOW", "userInteraction": "NONE", "scope": "UNCHANGED", "confidentialityImpact": "HIGH", "integrityImpact": "HIGH", "availabilityImpact": "HIGH", "baseScore": 7.0, "baseSeverity": "HIGH"}, "exploitabilityScore": 1.0, "impactScore": 5.9}], "cvssMetricV2": [{"source": "nvd@nist.gov", "type": "Primary", "cvssData": {"version": "2.0", "vectorString": "AV:L/AC:M/Au:N/C:C/I:C/A:C", "accessVector": "LOCAL", "accessComplexity": "MEDIUM", "authentication": "NONE", "confidentialityImpact": "COMPLETE", "integrityImpact": "COMPLETE", "availabilityImpact": "COMPLETE", "baseScore": 6.9}, "baseSeverity": "MEDIUM", "exploitabilityScore": 3.4, "impactScore": 10.0, "acInsufInfo": false, "obtainAllPrivilege": false, "obtainUserPrivilege": false, "obtainOtherPrivilege": false, "userInteractionRequired": false}]}, "weaknesses": [{"source": "nvd@nist.gov", "type": "Primary", "description": [{"lang": "en", "value": "CWE-77"}]}], "configurations": [{"nodes": [{"operator": "OR", "negate": false, "cpeMatch": [{"vulnerable": true, "criteria": "cpe:2.3:a:setroubleshoot_project:setroubleshoot:*:*:*:*:*:*:*:*", "versionEndIncluding": "-", "matchCriteriaId": "81FFD870-6377-4CE9-89C0-07EA99635370"}]}]}, {"nodes": [{"operator": "OR", "negate": false, "cpeMatch": [{"vulnerable": true, "criteria": "cpe:2.3:o:redhat:enterprise_linux_desktop:7.0:*:*:*:*:*:*:*", "matchCriteriaId": "33C068A4-3780-4EAB-A937-6082DF847564"}, {"vulnerable": true, "criteria": "cpe:2.3:o:redhat:enterprise_linux_hpc_node:7.0:*:*:*:*:*:*:*", "matchCriteriaId": "3C84489B-B08C-4854-8A12-D01B6E45CF79"}, {"vulnerable": true, "criteria": "cpe:2.3:o:redhat:enterprise_linux_server:7.0:*:*:*:*:*:*:*", "matchCriteriaId": "51EF4996-72F4-4FA4-814F-F5991E7A8318"}, {"vulnerable": true, "criteria": "cpe:2.3:o:redhat:enterprise_linux_workstation:7.0:*:*:*:*:*:*:*", "matchCriteriaId": "825ECE2D-E232-46E0-A047-074B34DB1E97"}]}]}], "references": [{"url": "http://seclists.org/oss-sec/2016/q2/574", "source": "secalert@redhat.com", "tags": ["Mailing List", "Third Party Advisory"]}, {"url": "http://securitytracker.com/id/1036144", "source": "secalert@redhat.com", "tags": ["Patch", "Third Party Advisory"]}, {"url": "https://access.redhat.com/errata/RHSA-2016:1293", "source": "secalert@redhat.com", "tags": ["Third Party Advisory"]}, {"url": "https://bugzilla.redhat.com/show_bug.cgi?id=1346461", "source": "secalert@redhat.com", "tags": ["Issue Tracking"]}, {"url": "https://github.com/fedora-selinux/setroubleshoot/commit/dda55aa50db95a25f0d919c3a0d5871827cdc40f", "source": "secalert@redhat.com", "tags": ["Patch"]}, {"url": "https://github.com/fedora-selinux/setroubleshoot/commit/e69378d7e82a503534d29c5939fa219341e8f2ad", "source": "secalert@redhat.com", "tags": ["Patch"]}, {"url": "https://rhn.redhat.com/errata/RHSA-2016-1267.html", "source": "secalert@redhat.com", "tags": ["Third Party Advisory"]}]}, "github_commit_url": "https://github.com/fedora-selinux/setroubleshoot/commit/dda55aa50db95a25f0d919c3a0d5871827cdc40f"}}