{"buggy_code": ["from flask import current_app, request\nfrom flask_restful import Resource, abort\nfrom dns import reversename, rdatatype\nfrom dns.resolver import NXDOMAIN, NoNameservers\n\nfrom resolverapi.util import is_valid_hostname, is_valid_rdtype, is_valid_ip\nfrom resolverapi.util.dns_query import parse_query\nfrom resolverapi import dns_resolver\n\nimport time\nfrom dns.exception import Timeout\n\n\nclass LookupRecordType(Resource):\n\n    def get(self, rdtype, domain):\n        t1 = time.time()\n\n        rdtype = rdtype.upper()\n        current_app.logger.info(\n            'Request from %s - %s %s', request.remote_addr, rdtype, domain)\n        self.valid_args(rdtype, domain)\n\n        # Iterate through nameservers so that we can tell which one gets used.\n        nameservers = current_app.config['RESOLVERS']\n        for nameserver in nameservers:\n            dns_resolver.nameservers = [nameserver]\n            try:\n                answer = dns_resolver.query(\n                    domain, rdtype, raise_on_no_answer=False)\n                # Successful query\n                break\n            except (NoNameservers, NXDOMAIN):\n                # TODO: this should still follow the RFC\n                return {'message': \"No nameservers for %s\" % domain}, 404\n            except Timeout as e:\n                # Communication fail or timeout - try next nameserver\n                if nameserver is nameservers[-1]:\n                    current_app.logger.info(e)\n                    return {'message': 'All nameservers timed out.'}, 503\n                continue\n            except Exception as e:\n                current_app.logger.error(e)\n                return {'message': 'An unexpected error occured.'}, 500\n\n        t2 = time.time()\n        duration = t2 - t1\n\n        return parse_query(answer, nameserver, duration)\n\n    def valid_args(self, rdtype, domain):\n        if not is_valid_rdtype(rdtype):\n            abort(400, message=\"%s type is not supported\" % rdtype)\n        if not is_valid_hostname(domain):\n            abort(400, message=\"%s is not a valid domain name\" % domain)\n\n\nclass ReverseLookup(Resource):\n\n    def get(self, ip):\n        t1 = time.time()\n        self.valid_args(ip)\n\n        # Iterate through nameservers so that we can tell which one gets used.\n        nameservers = current_app.config['RESOLVERS']\n        for nameserver in nameservers:\n            dns_resolver.nameservers = [nameserver]\n            try:\n                # http://stackoverflow.com/a/19867936/1707152\n                answer = dns_resolver.query(\n                    reversename.from_address(ip), rdatatype.PTR,\n                    raise_on_no_answer=False)\n                # Successful query\n                break\n            except Timeout as e:\n                # Communication fail or timeout - try next nameserver\n                if nameserver is nameservers[-1]:\n                    current_app.logger.info(e)\n                    return {'message': 'All nameservers timed out.'}, 503\n                continue\n            except NXDOMAIN:\n                return {'message': 'No nameserver found for %s' % ip}, 404\n            except Exception as e:\n                current_app.logger.error(e)\n                return {'message': 'An unexpected error occured.'}, 500\n\n        t2 = time.time()\n        duration = t2 - t1\n\n        if answer is None:\n            return {'message': 'An unexpected error occured.'}, 500\n        return parse_query(answer, nameserver, duration)\n\n    def valid_args(self, ip):\n        if not is_valid_ip(ip):\n            abort(400, message=\"%s is not a valid ip address\" % ip)\n"], "fixing_code": ["from flask import current_app, request\nfrom flask_restful import Resource, abort\nfrom dns import reversename, rdatatype\nfrom dns.resolver import NXDOMAIN, NoNameservers\n\nfrom resolverapi.util import is_valid_hostname, is_valid_rdtype, is_valid_ip\nfrom resolverapi.util.dns_query import parse_query\nfrom resolverapi import dns_resolver\n\nimport time\nfrom dns.exception import Timeout\n\n\nclass LookupRecordType(Resource):\n\n    def get(self, rdtype, domain):\n        t1 = time.time()\n\n        rdtype = rdtype.upper()\n        current_app.logger.info(\n            'Request from %s - %s', request.remote_addr, rdtype)\n        self.valid_args(rdtype, domain)\n\n        # Iterate through nameservers so that we can tell which one gets used.\n        nameservers = current_app.config['RESOLVERS']\n        for nameserver in nameservers:\n            dns_resolver.nameservers = [nameserver]\n            try:\n                answer = dns_resolver.query(\n                    domain, rdtype, raise_on_no_answer=False)\n                # Successful query\n                break\n            except (NoNameservers, NXDOMAIN):\n                # TODO: this should still follow the RFC\n                return {'message': \"No nameservers for %s\" % domain}, 404\n            except Timeout as e:\n                # Communication fail or timeout - try next nameserver\n                if nameserver is nameservers[-1]:\n                    current_app.logger.info(e)\n                    return {'message': 'All nameservers timed out.'}, 503\n                continue\n            except Exception as e:\n                current_app.logger.error(e)\n                return {'message': 'An unexpected error occured.'}, 500\n\n        t2 = time.time()\n        duration = t2 - t1\n\n        return parse_query(answer, nameserver, duration)\n\n    def valid_args(self, rdtype, domain):\n        if not is_valid_rdtype(rdtype):\n            abort(400, message=\"%s type is not supported\" % rdtype)\n        if not is_valid_hostname(domain):\n            abort(400, message=\"%s is not a valid domain name\" % domain)\n\n\nclass ReverseLookup(Resource):\n\n    def get(self, ip):\n        t1 = time.time()\n        self.valid_args(ip)\n\n        # Iterate through nameservers so that we can tell which one gets used.\n        nameservers = current_app.config['RESOLVERS']\n        for nameserver in nameservers:\n            dns_resolver.nameservers = [nameserver]\n            try:\n                # http://stackoverflow.com/a/19867936/1707152\n                answer = dns_resolver.query(\n                    reversename.from_address(ip), rdatatype.PTR,\n                    raise_on_no_answer=False)\n                # Successful query\n                break\n            except Timeout as e:\n                # Communication fail or timeout - try next nameserver\n                if nameserver is nameservers[-1]:\n                    current_app.logger.info(e)\n                    return {'message': 'All nameservers timed out.'}, 503\n                continue\n            except NXDOMAIN:\n                return {'message': 'No nameserver found for %s' % ip}, 404\n            except Exception as e:\n                current_app.logger.error(e)\n                return {'message': 'An unexpected error occured.'}, 500\n\n        t2 = time.time()\n        duration = t2 - t1\n\n        if answer is None:\n            return {'message': 'An unexpected error occured.'}, 500\n        return parse_query(answer, nameserver, duration)\n\n    def valid_args(self, ip):\n        if not is_valid_ip(ip):\n            abort(400, message=\"%s is not a valid ip address\" % ip)\n"], "filenames": ["resolverapi/endpoints.py"], "buggy_code_start_loc": [21], "buggy_code_end_loc": [22], "fixing_code_start_loc": [21], "fixing_code_end_loc": [22], "type": "CWE-116", "message": "A vulnerability classified as problematic has been found in OpenDNS OpenResolve. This affects an unknown part of the file resolverapi/endpoints.py. The manipulation leads to improper output neutralization for logs. The name of the patch is 9eba6ba5abd89d0e36a008921eb307fcef8c5311. It is recommended to apply a patch to fix this issue. The identifier VDB-217197 was assigned to this vulnerability.", "other": {"cve": {"id": "CVE-2015-10011", "sourceIdentifier": "cna@vuldb.com", "published": "2023-01-02T22:15:15.323", "lastModified": "2023-01-09T19:22:02.903", "vulnStatus": "Analyzed", "descriptions": [{"lang": "en", "value": "A vulnerability classified as problematic has been found in OpenDNS OpenResolve. This affects an unknown part of the file resolverapi/endpoints.py. The manipulation leads to improper output neutralization for logs. The name of the patch is 9eba6ba5abd89d0e36a008921eb307fcef8c5311. It is recommended to apply a patch to fix this issue. The identifier VDB-217197 was assigned to this vulnerability."}], "metrics": {"cvssMetricV31": [{"source": "nvd@nist.gov", "type": "Primary", "cvssData": {"version": "3.1", "vectorString": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H", "attackVector": "NETWORK", "attackComplexity": "LOW", "privilegesRequired": "NONE", "userInteraction": "NONE", "scope": "UNCHANGED", "confidentialityImpact": "HIGH", "integrityImpact": "HIGH", "availabilityImpact": "HIGH", "baseScore": 9.8, "baseSeverity": "CRITICAL"}, "exploitabilityScore": 3.9, "impactScore": 5.9}], "cvssMetricV30": [{"source": "cna@vuldb.com", "type": "Secondary", "cvssData": {"version": "3.0", "vectorString": "CVSS:3.0/AV:A/AC:L/PR:L/UI:N/S:U/C:N/I:L/A:L", "attackVector": "ADJACENT_NETWORK", "attackComplexity": "LOW", "privilegesRequired": "LOW", "userInteraction": "NONE", "scope": "UNCHANGED", "confidentialityImpact": "NONE", "integrityImpact": "LOW", "availabilityImpact": "LOW", "baseScore": 4.6, "baseSeverity": "MEDIUM"}, "exploitabilityScore": 2.1, "impactScore": 2.5}], "cvssMetricV2": [{"source": "cna@vuldb.com", "type": "Secondary", "cvssData": {"version": "2.0", "vectorString": "AV:A/AC:L/Au:S/C:N/I:P/A:P", "accessVector": "ADJACENT_NETWORK", "accessComplexity": "LOW", "authentication": "SINGLE", "confidentialityImpact": "NONE", "integrityImpact": "PARTIAL", "availabilityImpact": "PARTIAL", "baseScore": 4.1}, "baseSeverity": "MEDIUM", "exploitabilityScore": 5.1, "impactScore": 4.9, "acInsufInfo": false, "obtainAllPrivilege": false, "obtainUserPrivilege": false, "obtainOtherPrivilege": false, "userInteractionRequired": false}]}, "weaknesses": [{"source": "nvd@nist.gov", "type": "Primary", "description": [{"lang": "en", "value": "CWE-116"}]}, {"source": "cna@vuldb.com", "type": "Secondary", "description": [{"lang": "en", "value": "CWE-117"}]}], "configurations": [{"nodes": [{"operator": "OR", "negate": false, "cpeMatch": [{"vulnerable": true, "criteria": "cpe:2.3:a:cisco:openresolve:*:*:*:*:*:*:*:*", "versionEndExcluding": "2015-08-03", "matchCriteriaId": "3777CAAC-B752-4033-AD3C-5C878DA0E998"}]}]}], "references": [{"url": "https://github.com/opendns/OpenResolve/commit/9eba6ba5abd89d0e36a008921eb307fcef8c5311", "source": "cna@vuldb.com", "tags": ["Patch", "Third Party Advisory"]}, {"url": "https://vuldb.com/?ctiid.217197", "source": "cna@vuldb.com", "tags": ["Permissions Required", "Third Party Advisory"]}, {"url": "https://vuldb.com/?id.217197", "source": "cna@vuldb.com", "tags": ["Permissions Required", "Third Party Advisory"]}]}, "github_commit_url": "https://github.com/opendns/OpenResolve/commit/9eba6ba5abd89d0e36a008921eb307fcef8c5311"}}